### ISSUE TITLE
doc: libdnet needed (at least on Darwin)

### ISSUE THREAD

**Issue by shaunc** [ofalk/scanssh#5]
On osx, I was able to install, but needed to do

    brew install libdnet

first... (as well as install libevent, as mentioned in the doc)

**Comment by ofalk** [comment]
@shaunc Where do you expect this to be documented?
It's documented here: https://github.com/ofalk/scanssh/wiki
As well as in the README.md: https://github.com/ofalk/scanssh/blob/master/README.md
Let me know - I'll be happy to add document it wherever it makes sense!

**Comment by shaunc** [comment]
um... I guess I'm blind! Or I can only read two lines of prerequisites, and that was on the third line. :)

... sorry ...

**Comment by ofalk** [comment]
OK, @shaunc - thanks for the fast feedback! :+1:
